### ISSUE TITLE
Log refresh create/update statements to stdout not stderr

### ISSUE THREAD

**Issue by traceyn** [abletech/easy_reference_data#9]
Hello lovely Abletech developers!

When records are refreshed this gem sends puts statements to stderr. This happens when successfully creating or updating a record, not for error/exception scenarios. These end up in our logs looking like errors and effecting our error monitors.

Would you please consider changing them to stdout instead of stderr?

Thanks!

**Comment by caasssandre** [comment]
Hi Tracey,
Thanks for raising this, I'll look into it now :)

**Comment by caasssandre** [comment]
This is now solved, please update to 1.2.1. Thank you @traceyn !

**Comment by traceyn** [comment]
Amazing, thanks so much!
